version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://szayqztc:ujDtQwXZ_0Vh5gqfDz3zQWIOgQbSOgNI@silly.db.elephantsql.com/szayqztc
    ports:
      - "4000:4000"
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: szayqztc
      POSTGRES_PASSWORD: ujDtQwXZ_0Vh5gqfDz3zQWIOgQbSOgNI
      POSTGRES_DB: szayqztc      
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    restart: unless-stopped
