version: '3.7'

services:
  app:
    container_name: nestjs-docker
    build:
      context: ..
      dockerfile: docker/Dockerfile

    ports:
      - 3000:3000

    volumes:
      - ../:/usr/src/app

